### ISSUE TITLE
libmm-plugin-ccpm.so fails basic intercept test.

### ISSUE THREAD

**Issue by dwaddington** [IBM/mcas#122]
The following basic test can be used to test a plugin:

PLUGIN=dist/lib/libmm-plugin-ccpm.so LD_PRELOAD=dist/lib/libmm.so src/lib/libmm/mmwrapper-test-prog

Running, this fails with:

$ PLUGIN=dist/lib/libmm-plugin-ccpm.so LD_PRELOAD=dist/lib/libmm.so src/lib/libmm/mmwrapper-test-prog
free(): invalid pointer
Aborted (core dumped)

**Comment by dwaddington** [comment]
Debug with:
gdb -ex 'set env PLUGIN dist/lib/libmm-plugin-passthru.so' -ex 'set env LD_PRELOAD dist/lib/libmm.so' src/lib/libmm/mmwrapper-test-prog

**Comment by dwaddington** [comment]
I wonder if it is to do with free(NULL) which by POSIX semantics will do nothing. In CCPM it fails.

**Comment by dwaddington** [comment]
libmm-plugin-rcalb can be used as a reference point.

**Comment by dwaddington** [comment]
Clem, there should not be any "numa awareness" support in the plugin.

(gdb) 
#3  0x00007fda2793c5ec in malloc_printerr () from /lib64/libc.so.6
(gdb) 
#4  0x00007fda2793deec in _int_free () from /lib64/libc.so.6
(gdb) 
#5  0x00007fda26c6bc3f in numa_init () from /lib64/libnuma.so.1
(gdb) 
#6  0x00007fda289cb87a in call_init.part () from /lib64/ld-linux-x86-64.so.2
(gdb)

**Comment by dickeycl** [comment]
Due to sue of libnuma, which is needed by libpmem, which is needed by ccpm to persist data. I will try to decouple the "persist" function from ccpm.

**Comment by dwaddington** [comment]
Test now passes after fixes in commit: 55a83e042402bceb335f9c72c3ba5e766eeca55f

$ PLUGIN=dist/lib/libmm-plugin-ccpm.so LD_PRELOAD=dist/lib/libmm.so src/lib/libmm/mmwrapper-test-prog
> Test prog.
Performing 1MB mallocs ...
Freeing previous allocs ...
Performing random 8-64B mallocs ...
Freeing previous allocs ...
Performing large malloc ...
> allocating 4194304 bytes
> result of malloc: p=0xaa01400000
Performing calloc ...
>result of calloc: p=0xaa001f4000
> Done.
