### ISSUE TITLE
Tabulator_ccpm test re-run fails

### ISSUE THREAD

**Issue by dwaddington** [IBM/mcas#145]
The demo runs once.  Leaving the server alive, when the client is re-run a lock up is observed on the server (suggesting ADO SEGV).

Running with USE_GDB=1 USE_XTERM=1 the re-run appears to be OK.

**Comment by dwaddington** [comment]
DAX_RESET=1 USE_ODP=1 ./dist/bin/mcas --conf ./dist/conf/tabulator-ccpm.conf

Client:

./dist/bin/./dist/bin/tabulator_ccpm_test.sh  <server-ip-addr>

**Comment by dwaddington** [comment]
The ADO seems to die around cc->add(&count, sizeof(double))

**Comment by dwaddington** [comment]
If the cc->add calls are removed, then the recovery works.  I checked the ccv pointer and it is correctly recovered.

**Comment by dwaddington** [comment]
Clem will need to take a look at this, since it looks to be in the libccpm code.

**Comment by dickeycl** [comment]
Minor item: I see a zombie process after exiting the client the first time. The server should probably have cleaned it up.

**Comment by dickeycl** [comment]
The second client did leave a core file on aep2b. aep2b is configured to let coredumpctl handle core dumps. The failing line is
src/lib/libccpm/src/log.cpp:312
  _mr->allocate(p, sizeof(block_header) + block_size, sizeof(void *));

_mr is in PM, which is not part of the core dump:
(gdb) p/x &_mr
$10 = 0x100003e04e8

But the failing instruction is a load from DRAM
(gdb) x/i $pc
=> 0x7fa33d9640d7 <log::extend+95>:	mov    (%rax),%rdx
(gdb) x/gx $rax
0x17b1990:	Cannot access memory at address 0x17b1990

This part of vft lookup, so it's probably another case of a stale vft

=> 0x7fa33d9640d7 <log::extend+95>:	mov    (%rax),%rdx ; vft address to rdx
   0x7fa33d9640da <log::extend+98>:	add    $0x18,%rdx ; offset to the allocate fn ptr
   0x7fa33d9640de <log::extend+102>:	mov    (%rdx),%r8 ; fetch allocate fn ptr
   ...
   0x7fa33d9640f5 <log::extend+125>:	callq  *%r8 ; call allocate

**Comment by dwaddington** [comment]
Fix commit https://github.com/IBM/mcas/commit/fd03828ae1d261d3a8ab503a67aa280c552a3c54
