### ISSUE TITLE
mapstore pool expansion in combination with MAPSTORE_BACKING_STORE_DIR

### ISSUE THREAD

**Issue by dwaddington** [IBM/mcas#178]
The logic is incorrect since it tries to create a file of the same name. SIGBUS results.

**Comment by dickeycl** [comment]
Perhaps each memory "source" should have its own allocation mechanism: backing store: ftruncate+mmap; local DRAM: mmap(MAP_ANONYMOUS), numa (eventually): numa_alloc_onnode.

**Comment by dickeycl** [comment]
Likely fixed by commit 136bcb6, which uses ftruncate to extend the backing store if a backing store is being used.

**Comment by dickeycl** [comment]
Fixed

**Comment by dickeycl** [comment]
Fixed by 136bcb6
