### ISSUE TITLE
Double free error.

### ISSUE THREAD

**Issue by dwaddington** [IBM/mcas#179]
Clem; in developing the libkvstore (C wrapper to C++ store components) I ran into an issue with hstore.
The issue is double free on the value pointer returned from a get call.

to run
use EPIC-24 branch

then.. 
```
danielwaddington:libkvstore$ pwd
/home/danielwaddington/mcas/build/src/lib/libkvstore
danielwaddington:libkvstore$ rm /mnt/pmem0/*
danielwaddington:libkvstore$ ./unit_test/kvstore-wrapper-test-2
```

which gives ...
```LOG]: HSTORE put /home/danielwaddington/mcas/src/components/store/hstore/src/hstore.cpp:340 0x16d6950 (key=key-6) (value=value-of-6) 
[LOG]: HSTORE put /home/danielwaddington/mcas/src/components/store/hstore/src/hstore.cpp:340 0x16d6950 (key=key-7) (value=value-of-7) 
[LOG]: HSTORE put /home/danielwaddington/mcas/src/components/store/hstore/src/hstore.cpp:340 0x16d6950 (key=key-8) (value=value-of-8) 
[LOG]: HSTORE put /home/danielwaddington/mcas/src/components/store/hstore/src/hstore.cpp:340 0x16d6950 (key=key-9) (value=value-of-9) 
key:(key-0) value:(value-of-0:10)
key:(key-1) value:(value-of-1:10)
key:(key-2) value:(value-of-2:10)
key:(key-3) value:(value-of-3:10)
key:(key-4) value:(value-of-4:10)
key:(key-5) value:(value-of-5:10)
key:(key-6) value:(value-of-6:10)
key:(key-7) value:(value-of-7:10)
key:(key-8) value:(value-of-8:10)
double free or corruption (!prev)
Aborted (core dumped)
```

The same test for mapstore (kvstore-wrapper-test) passes the test.

**Comment by dickeycl** [comment]
For IKVStore::get, hstore expects to allocate memory only when out_value is NULL. mapstore expects to allocate memory in all cases. The interface says:

@param out_value Value data (if null, component will allocate memory)
@param out_value_len Size of value in bytes

mapstore is correct if you consider only the parameter name (it is not in-out), but hstore is correct if you read the read the comment in parentheses.

Further, hstore assumes that if out_value is not zero, meaning a callersupplied buffer, out_value_len is the length of the buffer:

    /* Although not documented, assume that non-zero
     * out_value implies that out_value_len holds
     * the buffer's size.
     */

In any case the memory, if allocated, should be freed by IKVStore::free_memory and not by ::free.

**Comment by dwaddington** [comment]
I fixed the free to free_memory; no it is strangely reporting error -7 (key not found) on the second get.
we need to fix the consistency between hstore and mapstore here also (make mapstore do the same?)

**Comment by dickeycl** [comment]
In addition to the instructions above for recreate, env var MM_PLUGIN_PATH needs to be set:

MM_PLUGIN_PATH=libmm-plugin-rcalb.so ./unit_test/kvstore-wrapper-test-2

**Comment by dwaddington** [comment]
Yes it doesn't but it does tell you that. I am fixing the mapstore semantics now.

**Comment by dwaddington** [comment]
BTW, in your code, I don't think out_value_len should be modified if E_INSUFFICIENT_BUFFER is being sent back

**Comment by dickeycl** [comment]
E_INSUFFICIENT_BUFFER is the case where modifying out_value_len is most useful. The caller knows the initial value; he set it. But if that is buffer was not enough, how big should the value buffer be? Modifying out_value_len tells the caller that. Without that, the caller is left in the dark. (That much is copied from the design of the key-value interface in REXX.)

**Comment by dwaddington** [comment]
OK fair enough.

**Comment by dickeycl** [comment]
Changing the body of kvstore_get fixes the "key not found" error. The NULL for value was not making it all the way to hstore:

`{
  auto kvstore = reinterpret_cast<IKVStore *>(store_handle);
  return kvstore->get(pool_handle, key, *value, *value_len);
}
`

**Comment by dwaddington** [comment]
Let me try.

**Comment by dwaddington** [comment]
I just pushed the fix and some clean up on the test1.c and test2.c.  Still SEGV on hstore.

**Comment by dickeycl** [comment]
hstore crashes when you call grow_pool (or any of a number of other functions) on a closed pool. Working on that.

**Comment by dickeycl** [comment]
Reverting the MCAS-86 change (not checked in), test case line 209
  CHECK_OK(kvstore_allocate_pool_memory(store, pool, 1024, 0xFF, &p));
fails (and does not set p) because alignment requested is not a power of 2.

**Comment by dickeycl** [comment]
Made changes to hstore, map_store, dax_manager, and the test cases. hstore and map_store now pass their respective tests.

**Comment by dwaddington** [comment]
Clem, I am now confused why we have get() with "user provided" memory semantics, when we have get_direct() to do this very thing.  Should we modify get() to not support "user provided" semantics?

**Comment by dwaddington** [comment]
I think this has arisen because we used to try to keep the IMCAS compatible with IKVStore.

**Comment by dickeycl** [comment]
Both functions predate the github repository, so in a sense they have always been around. get_direct does indeed look more useful to IMCAS; it can avoid a copy. I would recommend not using get_direct on kvstore, as it provides no advantage. I'm agnostic on whether we should drop either. Dropping either would probably require small changes to hstore unit tests,

**Comment by dwaddington** [comment]
I think we should drop get_direct.  We can mark it deprecated to start with?

**Comment by dwaddington** [comment]
This is more difficult than first seems. We use IKVStore tests with the IMCAS client component, therefore removing get_direct is not that easy.
