### ISSUE TITLE
Clear memory on pool deletion

### ISSUE THREAD

**Issue by dwaddington** [IBM/mcas#185]
The ADO could be used to sniff the prior contents of persistent memory.  
Data in a pool should be cleared on deletion.

**Comment by dickeycl** [comment]
Perhaps also need to check that an ADO cannot sniff another KV store in the same address space. And, as we have discussed before, we should prevent an ADO from trashing its own KV index.

**Comment by dickeycl** [comment]
If I'm not mistaken, the clear of memory is required only for devdax. Other mechanisms (fsdax files, malloc memory and numa_alloc memory) are cleared by Linux.

**Comment by dwaddington** [comment]
Do you mean fsdax memory is clear on file delete? How do you know this?

**Comment by dwaddington** [comment]
> Perhaps also need to check that an ADO cannot sniff another KV store in the same address space. And, as we have discussed before, we should prevent an ADO from trashing its own KV index.

Under what conditions do you think a non-root ADO can sniff another pool - I don't think its possible due to subspace mapping from shard to ADO.
