### ISSUE TITLE
put_direct multi-buffer failing

### ISSUE THREAD

**Issue by dwaddington** [IBM/mcas#36]
When using multiple buffers for a post_send, an I/O error occurs.

**Comment by dwaddington** [comment]
See line 1603:
https://github.com/IBM/mcas/blob/master/src/components/client/mcas-client/src/connection.cpp

**Comment by dickeycl** [comment]
Using two buffers requires two "desc" values. The second was missing. Should be fixed now in MCAC-17 branch

**Comment by dwaddington** [comment]
see https://github.com/IBM/mcas/commit/e2f90241eca511a07975b24619f3ebc1856c3644
https://github.com/IBM/mcas/commit/f61508805ae21e38fd6050b31d23808df8e39405

**Comment by dwaddington** [comment]
Fixed. see patches in previous comment.
