### ISSUE TITLE
Address parameter for fsdax mode

### ISSUE THREAD

**Issue by dwaddington** [IBM/mcas#39]
When using hstore with fsdax, the JSON configuration paramter, "addr" under "dax_config" does not seem to be respected.
The default seems to be 0x10000000000

**Comment by dwaddington** [comment]
Looking at this further, I think its just the mapping to the ADO.  We should have a way to specify the virtual address mapping in the ADO space. @dickeycl where does this 0x10000000000 address get set?

**Comment by dickeycl** [comment]
src/lib/libnupm/src/dax_manager.cpp

It is rather cryptic:

  char *free_address_begin = reinterpret_cast<char *>(uintptr_t(1) << 40);
  auto free_address_end    = free_address_begin + (std::size_t(1) << 40);

Perhaps should jsut be 0x10000.....

**Comment by dickeycl** [comment]
The problem arose when two copies of hstore wanted to run in the same address space. There was no mechanism to allow their common ancestor to partition the fsdax mapping between them. There are two two parameters to IKVStore_factory::create, which constructs an hstore:

  static constexpr const char *k_dax_base = "dax_base";
  static constexpr const char *k_dax_size = "dax_size";

These allow a common ancestor to separate the spaces used by the two hstore instances.
