### ISSUE TITLE
Unreadable configuration.md file

### ISSUE THREAD

**Issue by dwaddington** [IBM/mcas#6]

**Comment by dickeycl** [comment]
Not sure in what sense this s unreadable The file is about 20% English and 80% JSON schema. One of the advantages of a JSON Schema is, per "https://json-schema.org/, Provides clear human- and machine-readable documentation." Should there be a pretty-printer to translate the schema into native HTML or markdown, for the benefit of people cannot read JSON but aspire to write JSON? Probably. But I have not found it.

**Comment by dwaddington** [comment]
Added blank line prior to first JSON section.  It is now fine.
