### ISSUE TITLE
Problem with deps/install script on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by maxkatzmann** [IBM/mcas#94]
When running the `install-apts-ubuntu-18.sh` script on Ubuntu 20.04.2 LTS, I encountered the following issue:
```
cp: cannot stat 'libgtest*': No such file or directory
```

This is caused by the following [line in the script](https://github.com/IBM/mcas/blob/db8e80beaabaad9f65c9ccd08502da096d63c970/deps/install-apts-ubuntu-18.sh#L42):
```
cp libgtest* /usr/lib/
```

I'm not sure whether this is an issue with the system version mismatch. Nevertheless, I was able to fix the problem by replacing the line with
```
find . -type f -name "libgtest*" -print | while read filename
do
    cp -p "${filename}" /usr/lib/
done
```

Best,
Max

**Comment by dwaddington** [comment]
Thanks Max. We've not done a huge amount of testing on Ubuntu 20.  We're moving towards using a googletest library that is built as part of the main build. See https://github.com/IBM/mcas/blob/master/.gitmodules
So any dependency on a system install of googletest should ultimately be removed.

**Comment by dwaddington** [comment]
Fix to remove gtest package installs. Commit 47ff333 in master.

**Comment by maxkatzmann** [comment]
Thanks!
